# Generated by Django 5.1.4 on 2024-12-25 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("ruName", models.CharField(max_length=64)),
                ("coefficient", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DamageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("ruName", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Sourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbriviature", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("ruName", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("ruName", models.CharField(max_length=64)),
                ("weight", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WeaponMasterProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("ruName", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="WeaponType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("ruName", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="WeaponPropertiesGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weaponPropertiesGroup",
                        to="handbook.weapon",
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="handbook.weapon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeaponProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ruName", models.CharField(max_length=64)),
                ("discription", models.TextField()),
                ("ruDiscription", models.TextField()),
                (
                    "haveproperty",
                    models.ManyToManyField(
                        through="handbook.WeaponPropertiesGroup", to="handbook.weapon"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="weaponpropertiesgroup",
            name="weaponProperty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="handbook.weaponproperty",
            ),
        ),
    ]
