# Generated by Django 5.1.4 on 2025-01-04 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0002_currency_damagetype_sourse_weapon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sourсe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbriviature", models.CharField(max_length=64, null=True)),
                ("name", models.CharField(max_length=64, null=True)),
                ("ru_name", models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Sourse",
        ),
        migrations.RemoveField(
            model_name="weaponproperty",
            name="haveproperty",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="ruName",
        ),
        migrations.RemoveField(
            model_name="damagetype",
            name="ruName",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="ruName",
        ),
        migrations.RemoveField(
            model_name="weaponmasterproperties",
            name="ruName",
        ),
        migrations.RemoveField(
            model_name="weaponproperty",
            name="ruDiscription",
        ),
        migrations.RemoveField(
            model_name="weaponproperty",
            name="ruName",
        ),
        migrations.RemoveField(
            model_name="weapontype",
            name="ruName",
        ),
        migrations.AddField(
            model_name="currency",
            name="ru_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="damagetype",
            name="ru_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="weapon",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="handbook.currency",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="damage_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="handbook.damagetype",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="ru_description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="weapon",
            name="ru_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="weapon",
            name="weapon_master_properties",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="handbook.weaponmasterproperties",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="weapon_property",
            field=models.ManyToManyField(
                null=True, related_name="properties", to="handbook.weaponproperty"
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="weapon_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="handbook.weapontype",
            ),
        ),
        migrations.AddField(
            model_name="weaponmasterproperties",
            name="ru_description",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="weaponmasterproperties",
            name="ru_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="weaponproperty",
            name="ru_discription",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="weaponproperty",
            name="ru_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="weapontype",
            name="ru_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="coefficient",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="damagetype",
            name="name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="weight",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="weaponmasterproperties",
            name="description",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="weaponmasterproperties",
            name="name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="weaponproperty",
            name="discription",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="weapontype",
            name="name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="weapon",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="handbook.sourсe",
            ),
        ),
        migrations.DeleteModel(
            name="WeaponPropertiesGroup",
        ),
    ]
