# Generated by Django 5.1.4 on 2025-01-19 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0003_sourсe_delete_sourse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Имя персонажа"
                    ),
                ),
                (
                    "player_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Имя игрока"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        blank=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "speed_walk",
                    models.IntegerField(
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Скорость",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="damage_type",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="source",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="weapon_master_properties",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="weapon_property",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="weapon_type",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
        migrations.DeleteModel(
            name="DamageType",
        ),
        migrations.DeleteModel(
            name="Sourсe",
        ),
        migrations.DeleteModel(
            name="WeaponMasterProperties",
        ),
        migrations.DeleteModel(
            name="WeaponProperty",
        ),
        migrations.DeleteModel(
            name="Weapon",
        ),
        migrations.DeleteModel(
            name="WeaponType",
        ),
    ]
