# Generated by Django 5.1.4 on 2025-01-19 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0004_charlist_remove_weapon_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charlist",
            name="speed_walk",
        ),
        migrations.AlterField(
            model_name="charlist",
            name="level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                validators=[django.core.validators.MaxValueValidator(20)],
                verbose_name="Уровень",
            ),
        ),
    ]
