# Generated by Django 5.1.4 on 2025-01-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0005_remove_charlist_speed_walk_alter_charlist_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="charlist",
            name="speed_fly",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Скорость полета"
            ),
            preserve_default=False,
        ),
    ]
