# Generated by Django 5.1.4 on 2025-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0006_charlist_speed_fly"),
    ]

    operations = [
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Состояние")),
                ("properties", models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name="charlist",
            name="dark_vision",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Тёмное зрение"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="charlist",
            name="speed_swim",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Скорость плавания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="charlist",
            name="speed_walk",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Скорость ходьбы"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="charlist",
            name="conditions",
            field=models.ManyToManyField(
                to="handbook.condition", verbose_name="Состояния"
            ),
        ),
    ]
