# Generated by Django 5.1.4 on 2025-01-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "handbook",
            "0007_condition_charlist_dark_vision_charlist_speed_swim_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Название"
                    ),
                ),
                (
                    "abbriviature",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Сокращенно"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="condition",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Состояние"),
        ),
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="handbook.source",
                        verbose_name="Источник",
                    ),
                ),
            ],
        ),
    ]
