# Generated by Django 5.1.4 on 2025-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0008_source_alter_condition_name_monster"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="monsterType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("abberation", "Абберация"),
                    ("beast", "Зверь"),
                    ("celestial", "Небожитель"),
                ],
                max_length=50,
            ),
        ),
    ]
