# Generated by Django 5.1.4 on 2025-01-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0009_monster_monstertype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monster",
            old_name="monsterType",
            new_name="monster_type",
        ),
    ]
