# Generated by Django 5.1.4 on 2025-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0010_rename_monstertype_monster_monster_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="conditions",
            field=models.ManyToManyField(
                to="handbook.condition", verbose_name="Состояния"
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="dark_vision",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Тёмное зрение"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monster",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Имя персонажа"
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="speed_fly",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Скорость полета"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monster",
            name="speed_swim",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Скорость плавания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monster",
            name="speed_walk",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Скорость ходьбы"
            ),
            preserve_default=False,
        ),
    ]
